name: deploy-test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-verions: '14'

    - name: Checkout
      uses: actions/checkout@main

    - name: install dependencies
      uses: npm install

    - name: build
      uses: npm run build

    - name: deploy
      uses: cd dist && git init && git checkout -b main && git commit -m 'deploy' && git push -f https://github.com/ktseo41/quotes-sharer main:gh-pages